#!/bin/bash

# ─────────────────────────────────────────────────────────────
#  Setup de Supabase — Be Clean PWA
#  Script para guiarte en obtener y configurar las API keys
# ─────────────────────────────────────────────────────────────

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Be Clean PWA — Configuración de Supabase                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Sigue estos pasos para conectar la app a tu base de datos:"
echo ""
echo "1️⃣  Abre https://supabase.com/dashboard"
echo ""
echo "2️⃣  Selecciona tu proyecto (o crea uno nuevo)"
echo ""
echo "3️⃣  Ve a: Settings → API"
echo ""
echo "4️⃣  En la sección 'Project API keys', verás dos claves:"
echo ""
echo "    📌 Project URL"
echo "       • Es la URL base de tu proyecto"
echo "       • Ejemplo: https://abcdefghijklmnop.supabase.co"
echo "       • Cópiala y pégala en: VITE_SUPABASE_URL"
echo ""
echo "    📌 anon public key"
echo "       • Es la clave pública — segura para exponer"
echo "       • Empieza con: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "       • Cópiala y pégala en: VITE_SUPABASE_ANON_KEY"
echo ""
echo "5️⃣  Abre el archivo .env en la raíz del proyecto:"
echo ""
echo "    nano .env"
echo ""
echo "    O usa VS Code:"
echo "    • Presiona Ctrl+P (o Cmd+P en Mac)"
echo "    • Escribe: .env"
echo "    • Presiona Enter"
echo ""
echo "6️⃣  Reemplaza los valores de ejemplo por los tuyos:"
echo ""
echo "    VITE_SUPABASE_URL=https://tu-project-id.supabase.co"
echo "    VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "    SUPABASE_PROJECT_URL=https://tu-project-id.supabase.co"
echo "    SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo ""
echo "7️⃣  Guarda el archivo (Ctrl+S o Cmd+S)"
echo ""
echo "8️⃣  Reinicia el servidor de desarrollo:"
echo ""
echo "    npm run dev -- --host"
echo ""
echo "✅ ¡Listo! La app debería conectarse a Supabase automáticamente."
echo ""
echo "❓ Si ves un aviso amarillo en la app, recarga la página."
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  Importante:"
echo "   • NO incluyas .env en git (ya está en .gitignore)"
echo "   • Para GitHub Actions, crea Secrets en:"
echo "     Settings → Secrets and variables → Actions"
echo ""
echo "════════════════════════════════════════════════════════════"
